config/routes.rb
Rails.application.routes.draw do
  resources :itens
  resources :carrinhos
  resources :instrumentos
  devise_for :users, controller: {
  	registrations:  'registrations'
  }
  root 'instrumentos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/instrumento.rb
class Instrumento < ApplicationRecord
    before_destroy :not_reference_by_any_iten
    belongs_to :user, optional: true
    has_many :itens
  
    mount_uploader :imagem, ImagemUploader
    serialize :imagem, JSON # If you use SQLite, add this line
  
    validates :titulo, :marca, :preco, :modelo, presence: true
    validates :descricao, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
    validates :titulo, length: { maximum: 140, too_long: "%{count} characters is the maximum aloud. "}
    validates :preco, length: { maximum: 7 }
  
    MARCA = %w{ Fender Gibson Epiphone ESP Martin Dean Taylor Jackson PRS  Ibanez Charvel Washburn }
    CONDICAO = %w{ Novo Excelente Usado Péssimo }
  
    private 
    def not_reference_by_any_iten
        unless itens.empty?
            errors.add(:base,"Lista de itens presentes")
            throw :abort
            
        end
    end

  end

app/controllers/instrumentos_controller.rb
class InstrumentosController < ApplicationController
  before_action :set_instrumento, only: [:show, :edit, :update, :destroy]

  # GET /instrumentos
  # GET /instrumentos.json
  def index
    @instrumentos = Instrumento.all.order("created_at desc")
  end

  # GET /instrumentos/1
  # GET /instrumentos/1.json
  def show
  end

  # GET /instrumentos/new
  def new
    @instrumento = current_user.instrumentos.build
  end

  # GET /instrumentos/1/edit
  def edit
  end

  # POST /instrumentos
  # POST /instrumentos.json
  def create
    @instrumento = current_user.instrumentos.build(instrumento_params)

    respond_to do |format|
      if @instrumento.save
        format.html { redirect_to @instrumento, notice: 'Instrumento was successfully created.' }
        format.json { render :show, status: :created, location: @instrumento }
      else
        format.html { render :new }
        format.json { render json: @instrumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instrumentos/1
  # PATCH/PUT /instrumentos/1.json
  def update
    respond_to do |format|
      if @instrumento.update(instrumento_params)
        format.html { redirect_to @instrumento, notice: 'Instrumento was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrumento }
      else
        format.html { render :edit }
        format.json { render json: @instrumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instrumentos/1
  # DELETE /instrumentos/1.json
  def destroy
    @instrumento.destroy
    respond_to do |format|
      format.html { redirect_to instrument_url, notice: 'Instrumento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrumento
      @instrumento = Instrumento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrumento_params
      params.require(:instrumento).permit(:marca, :modelo, :descricao, :condicao, :titulo, :preco, :imagem)
    end
end

app/helpers/instrumentos_helper.rb
module InstrumentosHelper
    def instrumento_author(instrumento)
		user_signed_in? && current_user.id == instrumento.user_id
		
	end
end

app/views/instrumentos/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @instrumento, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :titulo , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :preco, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :modelo, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :descricao, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Marca</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :marca, collection: Instrumento::MARCA, prompt: "Select marca" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Condição</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condicao, collection: Instrumento::CONDICAO, prompt: "Select condição" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
         </div>

        <div class="field">
          <div class="control">
            <label class="label">Adicione Imagens</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :imagem, as: :file, input_html: { class:"file-input instrumento-imagem" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Escolha um arquivo</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancelar', instrumentos_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/instrumentos/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editar Instrumento
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', instrumento: @instrumento %>
</div>

app/views/instrumentos/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Procure Instrumentos pelo Delay.com
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="instrumento-index-grid pt4">
  <% @instrumentos.each do |instrumento| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(instrumento.imagem_url(:thumb)), instrumento %>

      <% if instrumento.condicao? %>
        <div class="condicao">
          <span class="tag is-dark"><%= instrumento.condicao %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to instrumento.titulo, instrumento %></h3>

      <p class="has-text-gray fg pt1">Vendido por <%= instrumento.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(instrumento.preco) %></p>

      <% if instrumento_author(instrumento) %>
         <%= link_to 'Editar', edit_instrumento_path(instrumento), class: "button is-small" %>
         <%= link_to 'Deletar', instrumento, method: :delete, data: { confirm: "Você tem certeza?" }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/instrumentos/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Venda um Instrumento
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', instrumento: @instrumento %>
</div>

app/views/instrumentos/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @instrumento.titulo %></h1>

      <ul class="pv1">
        <% if @instrumento.marca? %>
        <li class="inline-block pr3"><%= @instrumento.marca %></li>
        <% end %>

        <li class="inline-block pr3"><%= @instrumento.modelo %></li>

        <% if @instrumento.condicao? %>
        <li class="inline-block pr3"><%= @instrumento.condicao %></li>
        <% end %>
      </ul>

      <div class="feature-image">
        <%= image_tag(@instrumento.imagem_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Descricao</h3>
      <%= @instrumento.descricao %>


      <h3 class="subtitle is-4 pt5">Especificação do Produto</h3>

      <table class="table is-narrow">
        <% if @instrumento.condicao %>
        <tr>
          <td class="has-text-weight-bold">Condição:</td>
          <td><%= @instrumento.condicao %></td>
        </tr>
        <% end %>

        <% if @instrumento.marca %>
          <tr>
            <td class="has-text-weight-bold">Marca:</td>
            <td><%= @instrumento.marca %></td>
          </tr>
        <% end %>

        <tr>
          <td class="has-text-weight-bold">Modelo:</td>
          <td><%= @instrumento.modelo %></td>
        </tr>
      </table>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@instrumento.preco) %></h4>
        <p class="has-text-centered mb4">Sold by <%= @instrumento.user.name %></p>
        <%= button_to 'Add to cart', line_item_path(instrumento_id: @instrumento), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>

  <% if instrumento_author(@instrumento) %>
    <%= link_to 'Editar', edit_instrumento_path(@instrumento), class: 'button' %>
  <% end %>
</section>