config/routes.rb
Rails.application.routes.draw do
  resources :itens
  resources :carrinhos
  resources :instrumentos
  devise_for :users, controller: {
  	registrations:  'registrations'
  }
  root 'instrumentos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/carrinho.rb
class Carrinho < ApplicationRecord
	has_many:itens, dependent: :destroy

	

	def add_instrumento(instumento)
		current_item = itens.find_by(instumento_id: instumento_id)
		if current_item
			current_item.increment(:quantity)
		else
			current_item = itens.build(instumento_id: instumento_id)
		end
		current_item
	end
	
end

app/controllers/carrinhos_controller.rb
class CarrinhosController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_carrinho
  before_action :set_carrinho, only: [:show, :edit, :update, :destroy]

  # GET /carrinhos
  # GET /carrinhos.json
  def index
    @carrinhos = Carrinho.all
  end

  # GET /carrinhos/1
  # GET /carrinhos/1.json
  def show
  end

  # GET /carrinhos/new
  def new
    @carrinho = Carrinho.new
  end

  # GET /carrinhos/1/edit
  def edit
  end

  # POST /carrinhos
  # POST /carrinhos.json
  def create
    @carrinho = Carrinho.new(carrinho_params)

    respond_to do |format|
      if @carrinho.save
        format.html { redirect_to @carrinho, notice: 'Carrinho was successfully created.' }
        format.json { render :show, status: :created, location: @carrinho }
      else
        format.html { render :new }
        format.json { render json: @carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carrinhos/1
  # PATCH/PUT /carrinhos/1.json
  def update
    respond_to do |format|
      if @carrinho.update(carrinho_params)
        format.html { redirect_to @carrinho, notice: 'Carrinho was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrinho }
      else
        format.html { render :edit }
        format.json { render json: @carrinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carrinhos/1
  # DELETE /carrinhos/1.json
  def destroy
    @carrinho.destroy if @carrinho.id == session[:carrinho_id]
    session[:carrinho_id] = nil
    respond_to do |format|
      format.html { redirect_to carrinhos_url, notice: 'Carrinho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrinho
      @carrinho = Carrinho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrinho_params
      params.fetch(:carrinho, {})
    end

    def invalid_carrinho
      logger.error "Tentativa de acesso inválido ao carrinho #{params[:id]}"
      redirect_to root_path, notice "Este carrinho não existe"
    end
end

app/helpers/carrinhos_helper.rb
module CarrinhosHelper
end

app/views/carrinhos/_form.html.erb
<%= simple_form_for(@carrinho) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carrinhos/edit.html.erb
<h1>Editing Carrinho</h1>

<%= render 'form', carrinho: @carrinho %>

<%= link_to 'Show', @carrinho %> |
<%= link_to 'Back', carrinhos_path %>

app/views/carrinhos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carrinhos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carrinhos.each do |carrinho| %>
      <tr>
        <td><%= link_to 'Show', carrinho %></td>
        <td><%= link_to 'Edit', edit_carrinho_path(carrinho) %></td>
        <td><%= link_to 'Destroy', carrinho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrinho', new_carrinho_path %>

app/views/carrinhos/new.html.erb
<h1>New Carrinho</h1>

<%= render 'form', carrinho: @carrinho %>

<%= link_to 'Back', carrinhos_path %>

app/views/carrinhos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_carrinho_path(@carrinho) %> |
<%= link_to 'Back', carrinhos_path %>