config/routes.rb
Rails.application.routes.draw do
  resources :itens
  resources :carrinhos
  resources :instrumentos
  devise_for :users, controller: {
  	registrations:  'registrations'
  }
  root 'instrumentos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/iten.rb
class Iten < ApplicationRecord
  belongs_to :instrumento
  belongs_to :carrinho
  
end

app/controllers/itens_controller.rb
class ItensController < ApplicationController
  include CarrinhoAtual

  before_action :set_iten, only: [:show, :edit, :update, :destroy]
  before_action :set_carrinho, only:[:create]
  # GET /itens
  # GET /itens.json
  def index
    @itens = Iten.all
  end

  # GET /itens/1
  # GET /itens/1.json
  def show
  end

  # GET /itens/new
  def new
    @iten = Iten.new
  end

  # GET /itens/1/edit
  def edit
  end

  # POST /itens
  # POST /itens.json
  def create
    instrumento = instrumento.find(params[:instrumento_id])
    @iten = @carrinho.add_instrummento(instrumento)

    respond_to do |format|
      if @iten.save
        format.html { redirect_to @iten, notice: 'Iten adicionado ao carrinho.' }
        format.json { render :show, status: :created, location: @iten }
      else
        format.html { render :new }
        format.json { render json: @iten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itens/1
  # PATCH/PUT /itens/1.json
  def update
    respond_to do |format|
      if @iten.update(iten_params)
        format.html { redirect_to @iten, notice: 'Iten was successfully updated.' }
        format.json { render :show, status: :ok, location: @iten }
      else
        format.html { render :edit }
        format.json { render json: @iten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itens/1
  # DELETE /itens/1.json
  def destroy
    @carrinho = carrinho.find(session[:carrinho_id])
    @iten.destroy
    respond_to do |format|
      format.html { redirect_to carrinho_path(@carrinho), notice: 'Iten was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iten
      @iten = Iten.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iten_params
      params.require(:iten).permit(:instrumento_id)
    end
end

app/helpers/itens_helper.rb
module ItensHelper
end

app/views/itens/_form.html.erb
<%= simple_form_for(@iten) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :instrumento %>
    <%= f.input :carrinho %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/itens/edit.html.erb
<h1>Editing Iten</h1>

<%= render 'form', iten: @iten %>

<%= link_to 'Show', @iten %> |
<%= link_to 'Back', itens_path %>

app/views/itens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Itens</h1>

<table>
  <thead>
    <tr>
      <th>Instrumento</th>
      <th>Carrinho</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @itens.each do |iten| %>
      <tr>
        <td><%= iten.instrumento_id %></td>
        <td><%= iten.carrinho %></td>
        <td><%= link_to 'Show', iten %></td>
        <td><%= link_to 'Edit', edit_iten_path(iten) %></td>
        <td><%= link_to 'Destroy', iten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iten', new_iten_path %>

app/views/itens/new.html.erb
<h1>New Iten</h1>

<%= render 'form', iten: @iten %>

<%= link_to 'Back', itens_path %>

app/views/itens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instrumento:</strong>
  <%= @iten.instrumento_id %>
</p>

<p>
  <strong>Carrinho:</strong>
  <%= @iten.carrinho %>
</p>

<%= link_to 'Edit', edit_iten_path(@iten) %> |
<%= link_to 'Back', itens_path %>